language: node_js
node_js: node
script: npm test && npm run prod:build && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

language:
  node_js
before_install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
